### ISSUE TITLE
[Feature Request] Recognize VPN (dis-)connects

### ISSUE THREAD

**Issue by timbruegmann** [FrankS77/PreProxyFS#2]
Would be great to catch the following exception when disconnecting from a VPN (e.g. company network) but leave the PreProxy running, but then ignore the proxy settings and directly connect (or maybe even have the option to load a backup different proxy setting). Also the scenario vice versa would be great (reconnect to VPN, then use the primary settings again)
 
[Thread-4] INFO de.fschullerer.preproxyfs.DistributeServer - Start DistributeServer on TCP port: 65000
Exception in thread "Thread-1" de.fschullerer.preproxyfs.PreProxyFSException: Error creating ProxyForwardServer socket, Program exit.
        at de.fschullerer.preproxyfs.ProxyForwardServer.run(ProxyForwardServer.java:117)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at de.fschullerer.preproxyfs.ForwardServerThread.<init>(ForwardServerThread.java:31)
        at de.fschullerer.preproxyfs.ProxyForwardServer.run(ProxyForwardServer.java:105)

**Comment by FrankS77** [comment]
Feature is already published. Please see latest release and the new property: TIMEOUT_FOR_PROXY_CHECK
